Add missing (require 'ert) for ert-deftest
Although the ert-deftest macro is autoloaded, the ert-set-test
function used in its expansion is not, leading to ‘Lisp
error: (void-function ert-set-test)’.

Signed-off-by: Anders Kaseorg <andersk@mit.edu>